[project]
name = "family_tree_lite"
r_version = "4.5"

repositories = [
    { alias = "PPM", url = "https://packagemanager.posit.co/cran/latest" },
    { alias = "CRAN", url = "https://cloud.r-project.org" },
]

dependencies = [
    "base64enc",
    "bslib",
    "dplyr",
    "htmltools",
    "plotly",
    "shiny",
    "stringr",
    "tibble",
    "testthat",
    "jpeg",
    "png",
]
